ALTER TABLE users
    ADD COLUMN password_hash VARCHAR(60) NOT NULL DEFAULT 'placeholder-not-a-real-bcrypt-hash-000000000000000000000',
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER',
    ADD COLUMN date_of_birth DATE NOT NULL DEFAULT '1990-01-01';

ALTER TABLE users ALTER COLUMN password_hash DROP DEFAULT;
ALTER TABLE users ALTER COLUMN role DROP DEFAULT;
ALTER TABLE users ALTER COLUMN date_of_birth DROP DEFAULT;
